apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  namespace: minecraft
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.1.69/KubeStorage"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "minecraft"
  createSubDir: "true"  # optional: create a sub dir for new volume
reclaimPolicy: Retain  # only retain is supported
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
