apiVersion: apps/v1
kind: Deployment

metadata:
  name: sf3
  namespace: minecraft

  labels:
    app: sf3

spec:
  selector:
    matchLabels:
      app: sf3
  template:
    metadata:
      labels:
        app: sf3
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      volumes:
        - name: sf3
          hostPath:
            path: /media/raid1x2a/kube-storage/minecraft/sf3
      containers:
        - name: sf3
          image: thinkier/sf3
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - mountPath: /env
              name: sf3
          resources:
            requests:
              cpu: 1500m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 8Gi
