apiVersion: apps/v1
kind: Deployment

metadata:
  name: po3
  namespace: minecraft

  labels:
    app: po3

spec:
  selector:
    matchLabels:
      app: po3
  template:
    metadata:
      labels:
        app: po3
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      volumes:
        - name: po3
          hostPath:
            path: /media/raid1x2a/kube-storage/minecraft/po3
      containers:
        - name: po3
          image: thinkier/po3
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - mountPath: /env
              name: po3
          resources:
            requests:
              cpu: 750m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 6Gi
