apiVersion: apps/v1
kind: Deployment

metadata:
  name: bungee
  namespace: minecraft

  labels:
    app: bungee

spec:
  selector:
    matchLabels:
      app: bungee
  template:
    metadata:
      labels:
        app: bungee
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      volumes:
        - name: bungee
          hostPath:
            path: /media/raid1x2a/kube-storage/minecraft/bungee
      containers:
        - name: hexacord
          image: thinkier/hexacord
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - mountPath: /env
              name: bungee
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
