apiVersion: v1
kind: Service

metadata:
  name: bungee
  namespace: minecraft

spec:
  selector:
    app: bungee

  type: NodePort
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32565
